[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  VITE_FIREBASE_API_KEY = "AIzaSyDhZuInExe2qVK4Px3hsQ8VNRARcxvFm2Y"
  VITE_FIREBASE_AUTH_DOMAIN = "connetor-by-nova.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID = "connetor-by-nova"
  VITE_FIREBASE_STORAGE_BUCKET = "connetor-by-nova.firebasestorage.app"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "683556317411"
  VITE_FIREBASE_APP_ID = "1:683556317411:web:c03007d53a027791f03dd6"
  VITE_FIREBASE_MEASUREMENT_ID = "G-5R8CRKLXN5"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.gstatic.com https://www.googleapis.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://*.firebaseio.com https://*.googleapis.com https://identitytoolkit.googleapis.com wss://*.firebaseio.com; frame-src 'none';"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
